//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsCarPoolEntities1 : DbContext
    {
        public StudentsCarPoolEntities1()
            : base("name=StudentsCarPoolEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<preferabilityDay> preferabilityDays { get; set; }
        public virtual DbSet<Scheduling> Schedulings { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<PreferabilityArea> PreferabilityAreas { get; set; }
    }
}
