//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferabilityDay
    {
        public int DayPreferId { get; set; }
        public Nullable<int> IdDay { get; set; }
        public Nullable<int> LevelPriority { get; set; }
        public Nullable<int> IdParent { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
